## API Definitions
#server.servlet.context-path=/api
#server.port=4000
#
#  # MySQL Configurations
#spring.datasource.url=jdbc:mysql://localhost:3308/commerce-platform-accounts
#spring.datasource.username=develop
#spring.datasource.password=12345
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#  # Redis Configurations
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#
#  # Custom Definitions
#  ## Security
#security.jwt.expiration=3600000
#security.jwt.secret=$2a$12$yK6MT6MH.ALvfRt/t1/Qd.0f6GpWUQvNlfrh06ruzOIMIPm1D4qoe
#
#  ## Redis
#redis.recoverypassword.timeout=5
##
##server:
##  port: 4000
##  servlet:
##    context-path: /api
##
##spring:
##  datasource:
##    url: 'jdbc:mysql://localhost:3308/commerce-platform-accounts'
##    username: develop
##    password: 12345
##    driver-class-name: 'com.mysql.cj.jdbc.Driver'
##  jpa:
##    hibernate:
##      ddl-auto: update
